export const russianCyrillic = [
	{
		letterUpper: "А",
		letterLower: "а",
		pronunciation: "A",
		example: "Анна",
		meaning: "Anna (name)",
	},
  {
    letterUpper: "Б",
    letterLower: "б",
    pronunciation: "B",
    example: "Байкал",
    meaning: "(Lake) Baikal",
  },
  {
    letterUpper: "В",
    letterLower: "в",
    pronunciation: "V",
    example: "Волга",
    meaning: "Volga (River)",
  },
  {
    letterUpper: "Г",
    letterLower: "г",
    pronunciation: "G",
    example: "Гагарин",
    meaning: "Gagarin (Astronaut)",
  },
  {
    letterUpper: "Д",
    letterLower: "д",
    pronunciation: "D",
    example: "Достоевский",
    meaning: "Dostoevsky (Author)",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
  {
    letterUpper: "",
    letterLower: "",
    pronunciation: "",
    example: "",
    meaning: "",
  },
];
